name: playlist-manager
region: nyc

# Backend Service
services:
  - name: backend
    github:
      repo: your-username/your-repo
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: pnpm install && pnpm run build:backend
    run_command: pnpm --filter backend start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001

    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: HOST
        value: "0.0.0.0"
      - key: PNPM_VERSION
        value: "8.15.0"
      - key: DOWNLOAD_PATH
        value: "/tmp/downloads"
      - key: CLEANUP_AFTER_ZIP
        value: "true"
      - key: MAX_VIDEO_HEIGHT
        value: "720"
      - key: FRONTEND_URL
        value: "${frontend.PUBLIC_URL}"
      - key: YOUTUBE_CLIENT_ID
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: YOUTUBE_CLIENT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: OAUTH_REDIRECT_URI
        value: "${_self.PUBLIC_URL}/api/auth/callback"

    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5

  # Frontend Service
  - name: frontend
    github:
      repo: your-username/your-repo
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: pnpm install && pnpm run build:frontend
    run_command: pnpm --filter frontend start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000

    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: PNPM_VERSION
        value: "8.15.0"
      - key: NEXT_PUBLIC_API_URL
        value: "${backend.PUBLIC_URL}"
      - key: NEXT_PUBLIC_APP_NAME
        value: "Playlist Manager"
      - key: NEXT_PUBLIC_APP_VERSION
        value: "1.0.0"

    routes:
      - path: /
